[versions]
jacoco = "0.8.8"
junit = "5.9.2"

[libraries]
githubRelease-gradle = "com.github.breadmoirai:github-release:2.4.1"
nexusPublish-gradle = "io.github.gradle-nexus:publish-plugin:1.3.0"
semver4j-gradle = "com.vdurmont:semver4j:3.1.0"

slf4j-nop = { module = "org.slf4j:slf4j-nop", version = "1.7.36" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "1.7.36" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
assertj = "org.assertj:assertj-core:3.24.2"

[plugins]
gradleVersions = { id = "com.github.ben-manes.versions", version = "0.46.0" }
pluginPublishing = { id = "com.gradle.plugin-publish", version = "1.1.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.0" }
