/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.evantill;

/**
 * A library class.
 */
public class Library {

    /**
     * Some lib method
     * @return true
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
